#!/usr/bin/env bash

# This is a client side git hook
# For it to function, you must copy it into your local .git/hooks/ folder, with the below command (on Mac)
# cp .githooks/pre-commit  .git/hooks/

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(main|(format\\/|design\\/|algo\\/|algorithm\\/|knowledge\\/)[a-zA-Z0-9._-]+)$"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again. Read ReadMe file for more naming convention"

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0